set_property -dict {PACKAGE_PIN G21 IOSTANDARD LVCMOS33} [get_ports clk]
set_property -dict {PACKAGE_PIN U7 IOSTANDARD LVCMOS33} [get_ports rst]
set_property -dict {PACKAGE_PIN G22 IOSTANDARD LVCMOS33} [get_ports updown]

set_property -dict {PACKAGE_PIN F15 IOSTANDARD LVCMOS33} [get_ports out[3]]
set_property -dict {PACKAGE_PIN F13 IOSTANDARD LVCMOS33} [get_ports out[2]]
set_property -dict {PACKAGE_PIN F14 IOSTANDARD LVCMOS33} [get_ports out[1]]
set_property -dict {PACKAGE_PIN F16 IOSTANDARD LVCMOS33} [get_ports out[0]]

set_property -dict {PACKAGE_PIN D20 IOSTANDARD LVCMOS33} [get_ports a]
set_property -dict {PACKAGE_PIN C20 IOSTANDARD LVCMOS33} [get_ports b]
set_property -dict {PACKAGE_PIN C22 IOSTANDARD LVCMOS33} [get_ports c]
set_property -dict {PACKAGE_PIN B22 IOSTANDARD LVCMOS33} [get_ports d]
set_property -dict {PACKAGE_PIN B21 IOSTANDARD LVCMOS33} [get_ports e]
set_property -dict {PACKAGE_PIN A21 IOSTANDARD LVCMOS33} [get_ports f]
set_property -dict {PACKAGE_PIN E22 IOSTANDARD LVCMOS33} [get_ports g]
set_property -dict {PACKAGE_PIN D22 IOSTANDARD LVCMOS33} [get_ports dp]
set_property -dict {PACKAGE_PIN E14 IOSTANDARD LVCMOS33} [get_ports digit]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {clk_IBUF}]