set_property -dict {PACKAGE_PIN J4 IOSTANDARD LVCMOS33} [get_ports a3]
set_property -dict {PACKAGE_PIN L3 IOSTANDARD LVCMOS33} [get_ports a2]
set_property -dict {PACKAGE_PIN K3 IOSTANDARD LVCMOS33} [get_ports a1]
set_property -dict {PACKAGE_PIN M2 IOSTANDARD LVCMOS33} [get_ports a0]

set_property -dict {PACKAGE_PIN F15 IOSTANDARD LVCMOS33} [get_ports b1]
set_property -dict {PACKAGE_PIN F13 IOSTANDARD LVCMOS33} [get_ports b2]
set_property -dict {PACKAGE_PIN F14 IOSTANDARD LVCMOS33} [get_ports b3]
set_property -dict {PACKAGE_PIN F16 IOSTANDARD LVCMOS33} [get_ports b4]
set_property -dict {PACKAGE_PIN E17 IOSTANDARD LVCMOS33} [get_ports b5]
set_property -dict {PACKAGE_PIN C14 IOSTANDARD LVCMOS33} [get_ports b6]
set_property -dict {PACKAGE_PIN C15 IOSTANDARD LVCMOS33} [get_ports b7]
set_property -dict {PACKAGE_PIN E13 IOSTANDARD LVCMOS33} [get_ports b8]
set_property -dict {PACKAGE_PIN AA10 IOSTANDARD LVCMOS33} [get_ports b9]